name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af #@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Prepare Cache
        uses: Swatinem/rust-cache@v2

      - name: Check
        run: cargo check --verbose

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
